# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

config:
  validation: true
  warningsAsErrors: false

build:
  maxIssues: 10
  excludeCorrectable: false
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    active: false
    autoCorrect: true
    indentSize: 8
    maxLineLength: 120

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 5
  ComplexInterface:
    active: false
    threshold: 10
    includeStaticDeclarations: false
    includePrivateDeclarations: false
  ComplexMethod:
    active: true
    threshold: 15
    ignoreSingleWhenExpression: true
    ignoreSimpleWhenEntries: true
    ignoreNestingFunctions: false
    nestingFunctions:
      - 'apply'
      - 'forEach'
      - 'isNotNull'
      - 'ifNull'
      - 'run'
      - 'use'
      - 'with'

